//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteSystemDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coverage
    {
        public int Id { get; set; }
        public string CoverageName { get; set; }
        public int Deductible { get; set; }
        public int OccuranceLimit { get; set; }
        public int AggregateLimit { get; set; }
        public double CoveragePremium { get; set; }
        public int BusinessId { get; set; }
    
        public virtual Business Business { get; set; }
    }
}
