//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteSystemDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyTerm
    {
        public int Id { get; set; }
        public System.DateTime PolicyEffectiveDate { get; set; }
        public System.DateTime PolicyExpiryDate { get; set; }
    
        public virtual Quote Quote { get; set; }
    }
}
