//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteSystemDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuoteDataModelContainer : DbContext
    {
        public QuoteDataModelContainer()
            : base("name=QuoteDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<PolicyTerm> PolicyTerms { get; set; }
        public virtual DbSet<Prospect> Prospects { get; set; }
        public virtual DbSet<Business> Businesses { get; set; }
        public virtual DbSet<Coverage> Coverages { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<CodeValueList> CodeValueLists { get; set; }
        public virtual DbSet<CodeValue> CodeValues { get; set; }
    }
}
